# Generated by Django 3.1.6 on 2021-03-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210313_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
